### ISSUE TITLE
Margin in list on <Dropdown />

### ISSUE THREAD

**Issue by tcelestino** [catho/quantum#222]
![dropdown-mobile](https://user-images.githubusercontent.com/190265/78032116-09f94680-7354-11ea-913b-f31b93e00672.gif)

**Comment by alisson-suzigan** [comment]
Hi folks,
I'd like to try to fix this issue. Is that ok?

I saw that in the case of large texts with images (example of credit cards) the layout also breaks.
Did you see any other problems related to the Dropdown component with large texts?

**Comment by alisson-suzigan** [comment]
Another scenario: when the Dropdown component has 2 or more lines in its label, it changes the alignment from left to center. 
Is this the expected behavior or should the text stay on left in both cases?

![dd-closed-1-line](https://user-images.githubusercontent.com/5255042/92286495-2438e100-eeff-11ea-9a02-e6fc6809532d.png)
![dd-closed-2-lines](https://user-images.githubusercontent.com/5255042/92286497-24d17780-eeff-11ea-84ed-8e34fb2c0a86.png)

**Comment by rapahaeru** [comment]
Hi Alisson, how are you man? rs
so, answering your questions:

_Hi folks,
I'd like to try to fix this issue. Is that ok?

I saw that in the case of large texts with images (example of credit cards) the layout also breaks.
Did you see any other problems related to the Dropdown component with large texts?_

No! But with your second question, i think is yes!

_Another scenario: when the Dropdown component has 2 or more lines in its label, it changes the alignment from left to center.
Is this the expected behavior or should the text stay on left in both cases?_

I will consult the UX for this info, but i think he will say that is wrong. The text will be aligned in the left...

And thanks for your help!

**Comment by rapahaeru** [comment]
another thing, in the @tcelestino gif, the options was aligned in the left, but in yours, in center. Thats make me confused!
Whats the difference?

**Comment by alisson-suzigan** [comment]
In fact, they are 2 different cases:
1. the first one (reported by @tcelestino): affects the items in the dropdown list;
2. and the second one (reported by me): affects only the component placeholder;

**Comment by tcelestino** [comment]
published #256
